### ISSUE TITLE
Kafka consumer don't work anymore after refactoring

### ISSUE THREAD

**Issue by HontoNoRoger** [strimzi/client-examples#93]
I tried to change our previously existing env vars to match the new one after the refactorings.
However, even after following the renaming, an env var seem to be missing.

```
2022-12-23 09:36:00 INFO  KafkaConsumerExample:26 - KafkaConsumerConfig: KafkaConsumerConfig@70325e14
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value null for configuration key.deserializer: must be non-null.
	at org.apache.kafka.clients.consumer.ConsumerConfig.appendDeserializerToConfig(ConsumerConfig.java:615)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:647)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:627)
	at KafkaConsumerExample.main(KafkaConsumerExample.java:47)
```

This can be reproduced by the following:

1. Create a file `kafka-consumer.env` with the following content (taken from the [kafka-java-consumer.yaml](https://github.com/strimzi/client-examples/blob/main/java/kafka/java-kafka-consumer.yaml))
```
KAFKA_BOOTSTRAP_SERVERS=my-cluster-kafka-bootstrap:9092
STRIMZI_TOPIC=my-topic
KAFKA_GROUP_ID=my-java-kafka-consumer
STRIMZI_LOG_LEVEL=INFO
STRIMZI_MESSAGE_COUNT=1000000
```
2. Get latest container image with:
`docker pull quay.io/strimzi-examples/java-kafka-consumer:latest`
3. Start up a container with:
`docker run --rm -it --env-file=kafka-consumer.env quay.io/strimzi-examples/java-kafka-consumer:latest`

You'll get the same error message as above.

**Comment by scholzj** [comment]
Thanks for reporting this. I opened #94 to revert the changes to get this working.

**Comment by scholzj** [comment]
Ok, the CI passed now and the images were rebuilt. So it should now work as it did before the refactoring (i.e. with the old environment variables). Please let us know if you run into something more

@OwenCorrigan76 will have a look at fixing the YAMLs and we merge the refactoring again later. Thanks and sorry for the issue.
